Several years of changes since last commit, so don't expect a detailed commit log.
As usual, many bug have been fixed and small features have been added.

Noteworthy changes:

A new cross compiler toolchain and uclibc version (uclibc-ng) is used,
so some existing binaries might not run; all packages should to be rebuilt
and a new ipkg feed setup.

The build recipe has a new step.
   . exports board
   ./mktc.sh # build the cross toolchain -- only needs to be done once
   make

Most packages have been updated to their last versions (samba4 is standard),
and their download URLs updated (at the time of writing).

As the DNS-323/321 has not enought flash memory space to accomodate the updated
packages, a "dns-323-321-compat" pkg contains the missing pkgs and has to be
installed on disk to restore functionalities that users expect.

UBIFS is now used as the flash filesystem, meaning that packages can be
installed on flash memory instead of disk; you can remove packages that are
distributed in the firmware and you don't use or need, and install the ones
that you need.




git-svn-id: https://svn.code.sf.net/p/alt-f/code/trunk@3932 cd80dc97-fa67-4d1f-9ead-3176a861659d

diff --git a/alt-f/customroot/etc/init.d/S01power b/alt-f/customroot/etc/init.d/S01power
--- a/alt-f/customroot/etc/init.d/S01power
+++ b/alt-f/customroot/etc/init.d/S01power
@@ -1,10 +1,8 @@
 #!/bin/sh
 
 NAME=power
-
-CRONF=/var/spool/cron/crontabs/root
-
-#set -x
+DESC="Power Up/Down/Recovery Settings"
+REQUIRE="cron" # actually is cron() that implements require()
 
 . /etc/init.d/common
 
@@ -12,7 +10,7 @@ CRONF=/var/spool/cron/crontabs/root
 
 # this is not intended to be a user script, it is only convenient. It should only be executed once
 # - at boot, to setup the powerdown cron entry and the next powerup alarm if necessary
-# - and at powerdow, to set the next powerup alarm if necessary
+# - and at powerdown, to set the next powerup alarm if necessary
 # there are some possible issues: the next alarm elapses while the box is up and power fails
 # before the alarm is re-armed, power is not available when the alarm triggers, etc.
 #
@@ -20,38 +18,23 @@ CRONF=/var/spool/cron/crontabs/root
 #POWERUP_ALARM_SET="1 3 18 30" # if disabled, set to month day hour minute
 #POWERUP_AFTER_POWER_FAIL=1 # auto powerup after power fail. Default, recommended
 #POWERUP_ON_WOL=1 # powerup on WOL (wake on lan). Not working
-#POWERDOW_SET="0 21 * * 1,15" # cron entry for sheduled power down
+#POWERDOWN_SET="0 21 * * 1,15" # cron entry for sheduled power down
 #
-# The DNS-325 and DNS-320-Ax have the equivalent of
+# The DNS-325/DNS-320-Ax/DNR-322L have the equivalent of
 # POWERUP_AFTER_POWER_FAIL, which is set unconditionaly at rcS
 
+CMD="/usr/sbin/poweroff"
 
-
-if ! grep -qE "DNS-320-Bx|DNS-320L|DNS-327L" /tmp/board; then return 0; fi
-
-crondel() {
-	TF=$(mktemp -t)
-	crontab -l > $TF 2> /dev/null
-	sed -i '\|/usr/sbin/poweroff|d' $TF
-	touch -r $CRONF $TF
-	crontab $TF 2> /dev/null
-	touch -r $TF $CRONF
-	rm $TF
-}
+if ! grep -qE "DNS-320-Bx|DNS-320L|DNS-327L" /tmp/board; then
+	echo "$NAME: options not supported on this box"
+	return 1
+fi
 
 cronset() {
-	if test -n "$POWERDOW_SET"; then
-		require $NAME cron
-		TF=$(mktemp -t)
-		crontab -l > $TF 2> /dev/null
-		sed -i '\|/usr/sbin/poweroff|d' $TF
-		echo "$POWERDOW_SET /usr/sbin/poweroff #!# Alt-F cron" >> $TF
-		touch -r $CRONF $TF
-		crontab $TF 2> /dev/null
-		touch -r $TF $CRONF
-		rm $TF
+	if test -n "$POWERDOWN_SET"; then
+		cron add "$POWERDOWN_SET" $CMD
 	else
-		crondel
+		cron remove $CMD
 	fi
 }
 
@@ -68,68 +51,86 @@ rearm() {
 		dns320l-daemon -x  DisableWOL > /dev/null
 	fi
 
-	# alarm might be disabled, set it
-	if test -n "$POWERUP_ALARM_SET"; then
-		if dns320l-daemon -x readalarm | grep -q disabled; then
-			dns320l-daemon -x writealarm "$POWERUP_ALARM_SET" > /dev/null
+	if test -z "$POWERUP_ALARM_SET" -o -z "$POWERUP_ALARM_REPEAT"; then
+		dns320l-daemon -x writealarm disable > /dev/null
+	else
+		# alarm might be disabled, set it
+		if test -n "$POWERUP_ALARM_SET"; then
+			if dns320l-daemon -x readalarm | grep -q disabled; then
+				dns320l-daemon -x writealarm "$POWERUP_ALARM_SET" > /dev/null
+			fi
 		fi
-	fi
 
-	# alarm migh have elapsed, advance it to next event
-	if test -n "$POWERUP_ALARM_REPEAT"; then
-		res=$(dns320l-daemon -x readalarm)
-		while echo "$res"| grep -q 'elapsed'; do
-			res=$(dns320l-daemon -x writealarm "$POWERUP_ALARM_REPEAT")
-		done
-		echo $res
+		# alarm migh have elapsed, advance it to next event
+		if test -n "$POWERUP_ALARM_REPEAT"; then
+			res=$(dns320l-daemon -x readalarm)
+			rl=$( expr ${#POWERUP_ALARM_REPEAT} - 2)
+			if test "${POWERUP_ALARM_REPEAT:1:$rl}" -gt 0; then
+				while echo "$res"| grep -q 'elapsed'; do
+					res=$(dns320l-daemon -x writealarm "$POWERUP_ALARM_REPEAT")
+				done
+			fi
+			echo $res
+		fi
 	fi
 }
 
 case "$1" in
 	start)
-		echo -n "Starting $NAME: "
 		cronset
 		rearm
+		echo "Starting $NAME: OK."
 		;;
 	stop)
-		echo -n "Stopping $NAME: "
-		crondel
+		cron remove $CMD
 		rearm
+		echo "Stopping $NAME: OK."
 		;;
 	status)
-		echo "$NAME: "
-
+		echo "$DESC"
+		#Wakeup alarm disabled
+		#Wakeup alarm set to: 2023-12-04 02:17
 		alarm_res=$(dns320l-daemon -x readalarm)
-		echo $alarm_res | grep -qv 'disabled'; alarm_st=$?
-		echo "$alarm_res"
-
-		crontab -l | grep -q /usr/sbin/poweroff; spd_st=$?
-		if test $spd_st = 0; then
-			spd_res="Poweroff set to \"$(crontab -l | grep /usr/sbin/poweroff | cut -d" " -f1-5)\""
+		if $(echo $alarm_res | grep -q 'disabled'); then
+			alarm_st=1
+			echo -e "Schedule Power Up:\tNOT set"
 		else
-			spd_res="Poweroff NOT set"
+			alarm_st=0
+			alarm=$(echo $alarm_res | cut -d':' -f2-3)
+			echo -e "Scheduled Power Up:\tset to $alarm"
 		fi
-		echo "$spd_res"
+		#echo "$alarm_res"
+
+		crontab -l | grep -q $CMD; spd_st=$?
+		if test $spd_st = 0; then
+			spd_res="Scheduled Power Down:\tset to \"$(crontab -l | grep $CMD | cut -d" " -f1-5)\""
+		else
+			spd_res="Scheduled Power Down:\tNOT set"
+		fi
+		echo -e "$spd_res"
 
 		dns320l-daemon -x GetPowerRecoveryState | grep -q 128; apr_st=$?
 		if test $apr_st = 0; then
-			apr_res="Automatic Power Recovery set"
+			apr_res="Power Up after Power Cut:\tset"
 		else
-			apr_res="Automatic Power Recovery NOT set"
+			apr_res="Power Up after Power Cut:\tNOT set"
 		fi
-		echo "$apr_res"
+		echo -e "$apr_res"
 
 		dns320l-daemon -x GetWOLState | grep -q 1; wol_st=$?
 		if test $wol_st = 0; then
-			wol_res="Wake on Lan set"
+			wol_res="Power Up on Lan:\tset"
 		else
-			wol_res="Wake on Lan NOT set"
+			wol_res="Power Up on Lan:\tNOT set"
 		fi
-		echo "$wol_res"
+		echo -e "$wol_res"
 
-		if test $alarm_st = 0  -o $spd_st = 0 -o  $apr_st = 0 -o $wol_st = 0; then 
+#		if test $alarm_st = 0  -o $spd_st = 0 -o  $apr_st = 0 -o $wol_st = 0; then
+		if test $spd_st = 0; then # only scheduled power down affects return value
+			echo "$NAME running"
 			return 0
 		else
+			echo "$NAME stopped"
 			return 1
 		fi
 		;;
@@ -141,5 +142,5 @@ case "$1" in
 		cronset
 		rearm
 		;;
-	*) usage $0 "start|stop|status|restart|enable alarm|disable alarm" ;;
+	*) usage $0 "start|stop|status|restart" ;;
 esac
diff --git a/alt-f/customroot/etc/init.d/S31cacert b/alt-f/customroot/etc/init.d/S31cacert
--- a/alt-f/customroot/etc/init.d/S31cacert
+++ b/alt-f/customroot/etc/init.d/S31cacert
@@ -3,20 +3,21 @@
 DESC="Update CA certificates once a week"
 TYPE=net
 NAME=cacert
-#REQUIRE="cron" doesn't work here
+REQUIRE="cron" # actually is cron() that implements require()
 
 . /etc/init.d/common
 
 CMD="/usr/bin/update_ca.sh"
 
-# icron() to be removed after 1.1. Copied from common:cron()
+# FIXME icron() to be removed after 1.1. Copied from common:cron()
 CRONF=/var/spool/cron/crontabs/root
 icron() {
 	if test $# = 3; then cmd="$3"; else cmd="$2"; fi
+	
 	if test "$1" = "add"; then
 		TF=$(mktemp -t)
 		crontab -l > $TF 2> /dev/null
-		sed -i "\|$"cmd".*#!# Alt-F cron$|d" $TF
+		sed -i "\|$cmd.*#!# Alt-F cron$|d" $TF
 		if test $# = 3; then
 			tspec="$2"
 		else # once a week
@@ -32,6 +33,9 @@ icron() {
 		crontab $TF 2> /dev/null
 		touch -r $TF $CRONF
 		rm $TF
+		if ! rccron status >& /dev/null; then
+			rccron start # required to handle crontabs
+		fi
 	
 	elif test "$1" = "remove"; then
 		TF=$(mktemp -t)
@@ -41,25 +45,30 @@ icron() {
 		crontab $TF 2> /dev/null
 		touch -r $TF $CRONF
 		rm $TF
+		if ! test -s $CRONF; then
+			rccron stop # no crontab, cron not required
+		fi
+
 		
 	elif test "$1" = "status"; then
 		if ! rccron status >& /dev/null; then
 			echo "$NAME stopped"
 			return 1
 		elif crontab -l 2>/dev/null | grep -q "$2.*#!# Alt-F cron$"; then
-			echo "$NAME running"
+			rccron start >& /dev/null # required to handle the crontab
+			echo -e "$DESC\n$NAME running"
 			return 0
 		else
-			echo "$NAME stopped"
+			echo -e "$DESC\n$NAME stopped"
 			return 1
-		fi		
+		fi
 	fi
 }
 		
 istart() {
 	if ! readlink -f /Alt-F >& /dev/null; then
 		if ! aufs.sh -s >& /dev/null; then
-			echo -n "$NAME: /Alt-F folder not found, install Alt-F packages."
+			echo "$NAME: /Alt-F folder not found, CA updates not persistent, install Alt-F packages."
 			return 1
 		fi
 		aufs.sh -n
@@ -68,20 +77,23 @@ istart() {
 	fi
 }
 
+ACRON=cron
+if ! type cron >& /dev/null; then
+	ACRON=icron	
+fi
+
 case "$1" in
 	start)
 		istart $NAME
-		require $NAME cron
-		echo -n "Starting $NAME: "
-		icron add $CMD
-		echo "OK."
+		$CMD # prime the CA bundle, it might be the first usage since the pkg release
+		$ACRON add $CMD
+		echo "Starting $NAME: OK."
 		;;
 	stop)
-		echo -n "Stopping $NAME: "
-		icron remove $CMD
-		echo "OK."
+		$ACRON remove $CMD
+		echo "Stopping $NAME: OK."
 		;;
-	status) icron status $CMD ;;		
+	status) $ACRON status $CMD ;;		
 	restart) restart $NAME ;;
 	*) usage $0 "start|stop|status|restart" ;;
 esac
diff --git a/alt-f/customroot/etc/init.d/S44mysqld b/alt-f/customroot/etc/init.d/S44mysqld
--- a/alt-f/customroot/etc/init.d/S44mysqld
+++ b/alt-f/customroot/etc/init.d/S44mysqld
@@ -15,39 +15,61 @@ MYSQL_RUND=/var/run/$RC_USER
 MYSQL_LOGD=/var/log/$RC_USER
 MYSQL_LOG=$MYSQL_LOGD/$NAME.log
 MYSQL_CONFD=/etc/mysql
+MYSQL_CONF=$MYSQL_CONFD/my.cnf
+MYSQL_OPTS="--log-error=$MYSQL_LOG --general_log_file=$MYSQL_LOG --general_log=0"
+
+SSL_CERTS=/etc/ssl/certs
+SERRORL=/var/log/systemerror.log
 
 RC_PIDFILE=$MYSQL_RUND/$NAME.pid
 RC_START_BG=yes
 
 MYSQL_DIRS="$MYSQL_RUND $MYSQL_LOGD $MYSQL_CONFD"
- 
-for i in $MYSQL_DIRS; do
-	if ! test -d $i; then mkdir -p $i; fi
-done
+
+sinit() {
+	for i in $MYSQL_DIRS; do
+		if ! test -d $i; then mkdir -p $i; fi
+	done
+	# too early to call check_user()? see S52lighttpd
+	check_user $MYSQL_DIRS
+	
+	if ! test -f $SSL_CERTS/mysql.key; then
+		cp $SSL_CERTS/server.key $SSL_CERTS/mysql.key
+		chown mysql $SSL_CERTS/mysql.key
+	fi
+
+	if ! test -d $MYSQL_HOMED/$RC_USER; then
+		echo "Creating MySQL system tables..."
+		mysql_install_db --user=$RC_USER --datadir=$MYSQL_HOMED
+	fi
+}
 
 . /etc/init.d/common
 
-check_user $MYSQL_DIRS
-
 case "$1" in
 	start)
-		if ! test -d $MYSQL_HOMED/$RC_USER; then
-			echo "Creating MySQL system tables..."
-			mysql_install_db --user=$RC_USER --datadir=$MYSQL_HOMED
+		if ! status $NAME >& /dev/null; then
+			start mysqld_safe -- --pid-file=$RC_PIDFILE $MYSQL_OPTS
+			sleep 1
+		else
+			omsg 0
+			return 0;
 		fi
-
-		start mysqld_safe -- --pid-file=$RC_PIDFILE --log-error=$MYSQL_LOG
+		
+		if mysql -Be "" >& /dev/null; then		
+			emsg="<li>Assign a password to your $NAME root user.</li>"
+			pass=$(sed -n 's/^[[:space:]]*password[[:space:]]*=[[:space:]]*\(.*\)/\1/p' $MYSQL_CONF)
+			if test -z "$pass"; then
+				if ! grep -q "$emsg" $SERRORL; then 
+					echo "$emsg" >> $SERRORL
+				fi
+			else
+				sed -i '\|'"$emsg"'|d' $SERRORL 2> /dev/null
+			fi
+		fi
 		;;
-	stop)
-		stop $NAME
-		;;
-	status)
-		status $NAME
-		;;
-	restart)
-		restart $NAME
-		;;
-	*)
-		echo "Usage: $0 start|stop|status|restart"
-		;;
+	stop) stop $NAME ;;
+	status) status $NAME ;;
+	restart) restart $NAME ;;
+	*) usage $0 "start|stop|status|restart|init" ;;
 esac
diff --git a/alt-f/customroot/etc/init.d/S52lighttpd b/alt-f/customroot/etc/init.d/S52lighttpd
--- a/alt-f/customroot/etc/init.d/S52lighttpd
+++ b/alt-f/customroot/etc/init.d/S52lighttpd
@@ -5,78 +5,222 @@
 DESC="A secure, fast, compliant and very flexible web-server"
 TYPE=net
 NAME=lighttpd
+
 NEED_ALTF_DIR=1
-
-CONF_DIR=/etc/$NAME
-LOG_DIR=/var/log/$NAME 
-HOME_DIR=/var/lib/$NAME
-
-CONFF=$CONF_DIR/$NAME.conf
-
-SECR_DIGST=/etc/$NAME/lighttpd-digest.user
-SECR_RSYNC=/etc/rsyncd.secrets 
-VSFTPD_PEM=/etc/ssl/certs/vsftpd.pem
-LIGHTY_PEM=/etc/ssl/certs/lighttpd.pem
-BOX_PEM=/etc/ssl/certs/server.pem
-
 RC_USER=$NAME
 RC_USERN=35
 RC_GROUP=network
 RC_GROUPN=81
 RC_DESC="Lighttpd daemon"
 
+CONF_DIR=/etc/$NAME
+LOG_DIR=/var/log/$NAME 
+HOME_DIR=/var/lib/$NAME
+SOCK_DIR=$HOME_DIR/sockets
+ALPN_DIR=$HOME_DIR/tls-alpn
+
+CONF_LIGHTY=$CONF_DIR/$NAME.conf
+
+SECR_DIGST=/etc/$NAME/$NAME-digest.user
+SECR_RSYNC=/etc/rsyncd.secrets
+
+SSL_CERTS=/etc/ssl/certs
+LIGHTY_PEM=$SSL_CERTS/$NAME.pem
+BOX_PEM=$SSL_CERTS/server.pem
+
+CRON_CMD="/sbin/rclighttpd openports"
+
+digs_pass() {
+		realm="WebDAV"
+		while read ln; do
+			user=$(echo $ln | cut -d: -f1)
+			pass=$(echo $ln | cut -d: -f2)
+			if test -z "$user" -o -z "$pass" -o "${user:0:1}" = "#"; then continue; fi
+			hash=$(echo -n "$user:$realm:$pass" | md5sum | cut -b -32)
+			echo "$user:$realm:$hash" 
+		done < $SECR_RSYNC
+}
+
+sinit() {
+	# too early to call check_user()
+	if ! grep -q ^$RC_GROUP:x:$RC_GROUPN: /etc/group; then
+		addgroup -S -g $RC_GROUPN $RC_GROUP
+	fi
+	if ! id $RC_USER >& /dev/null; then
+		adduser -S -g "$RC_DESC" -G $RC_GROUP -u $RC_USERN -h /var/lib/$RC_USER $RC_USER
+	fi
+
+	if test -s $SECR_RSYNC; then
+		if ! test -e $SECR_DIGST; then touch $SECR_DIGST; fi
+		if test ! -s $SECR_DIGST -o $SECR_RSYNC -nt $SECR_DIGST; then
+			digs_pass > $SECR_DIGST
+			chown $RC_USER:$RC_GROUP $SECR_DIGST
+			chmod go-rwx $SECR_DIGST
+		fi
+	fi
+
+ 	if test -e $BOX_PEM -a ! -e $LIGHTY_PEM; then
+ 		ln -sf $BOX_PEM $LIGHTY_PEM
+ 	fi
+
+# 	ext_domain=$(sed -n 's/^var.ext_domain[[:space:]]*=[[:space:]]*"\([a-zA-Z0-9.-]*\)".*/\1/p' $CONF_LIGHTY)
+# 	if grep -q '^include.*ssl.conf' $CONF_LIGHTY; then ssl_en=y; fi
+# 	
+# 	if test -n "$ssl_en" -a \
+# 		! -f $SSL_CERTS/$ext_domain.crt -a ! -f $SSL_CERTS/$ext_domain.key; then
+# 		# using intranet cert for Lets Encript tls-alpn handshake.
+# 		# use cp not ln, as acme.sh uses cat to preserve perms.
+# 		cp $SSL_CERTS/server.crt $SSL_CERTS/$ext_domain.crt
+# 		cp $SSL_CERTS/server.key $SSL_CERTS/$ext_domain.key
+# 		cp $SSL_CERTS/rootCA.crt $SSL_CERTS/$ext_domain-ca.crt # hack
+# 	fi
+}
+
 . /etc/init.d/common
 
-if ! test -d $LOG_DIR; then
-	mkdir -p $LOG_DIR
+for i in $LOG_DIR $SOCK_DIR $ALPN_DIR; do
+	if ! test -d $i; then
+		mkdir -p $i
+	fi
+done
+
+check_user $LOG_DIR $HOME_DIR $CONF_LIGHTY
+
+# compat. conf files are not updated on a package update! This requires a re-install!
+if ! grep -q '^var.http_port' $CONF_LIGHTY; then
+	echo "$NAME: configuration files format have changed, you have to unistall and reinstall $NAME. Only configuration files will be affected."
+	exit 1
 fi
 
-if ! test -d $HOME_DIR/sockets; then
-	mkdir -p $HOME_DIR/sockets
-fi
-
-check_user $LOG_DIR $HOME_DIR $CONFF
-
-if test "$(sed -n 's|^var.server_root.*=.*"\(.*\)"|\1|p' $CONFF)" = "/Public"; then
+if test "$(sed -n 's|^var.server_root.*=.*"\(.*\)"|\1|p' $CONF_LIGHTY)" = "/Public"; then
 	echo "$NAME: you have to configure $NAME first."
 	exit 1
 fi
 
-digs_pass() {
-	realm="WebDAV"
-	while read ln; do
-    	user=$(echo $ln | cut -d: -f1)
-		pass=$(echo $ln | cut -d: -f2)
-		hash=$(echo -n "$user:$realm:$pass" | md5sum | cut -b -32)
-		echo "$user:$realm:$hash" 
-	done < $SECR_RSYNC
+# slow, internet based, migh disappear... but working since 2004!
+PORT_CHECKER=https://www.canyouseeme.org
+# $1-external port
+canyouseeme() {
+	if test -n "$1"; then
+		ok_res='color="green"><b>Success:</b>'
+		err_res='color="red"><b>Error:</b>'
+		res=$(wget -q --post-data port=$1 -O - $PORT_CHECKER)
+		if echo "$res" | grep -q $ok_res; then
+			echo " port $1 IS accessible from the internet."
+		elif  echo "$res" | grep -q $err_res; then
+			echo " port $1 is NOT accessible from the internet."
+			return 1
+		else
+			echo " Error: can't determine port $1 status."
+			return 1
+		fi
+	fi
 }
 
-istart() {
-	if test $SECR_RSYNC -nt $SECR_DIGST -o ! -f $SECR_DIGST; then
-		digs_pass > $SECR_DIGST
-		chown lighttpd $SECR_DIGST
-		chmod go-rwx $SECR_DIGST
-	fi
+# # If ISP blocks port might give false positives, as it only goes to the router.
+# # The router needs to support "Hairpinning", see wikipedia. faster but doubtful
+# # $1-external port
+# canyouseeme() {
+#     if test -n "$1"; then
+#     
+# 		PROTO=http
+# 		if test "$1" = 443; then PROTO=https; fi
+# 
+# 		if wget -q --no-check-certificate $PROTO://$ext_ip -O /dev/null; then
+# 			echo " port $1 IS accessible from the internet."
+# 			return 0
+# 		else
+# 			echo " port $1 is NOT accessible from the internet."
+# 		fi
+#     fi
+#     return 1
+# }
 
-	if ! test -e $BOX_PEM; then
-		ln $VSFTPD_PEM $BOX_PEM
-	fi
+router_ports() {
+	http_port=$(sed -n 's/^var.http_port[[:space:]]*=[[:space:]]*\([[:digit:]]*\).*/\1/p' $CONF_LIGHTY)
+	ext_http_port=$(sed -n 's/^var.ext_http_port[[:space:]]*=[[:space:]]*\([[:digit:]]*\).*/\1/p' $CONF_LIGHTY)
+	ext_http_en=$(sed -n 's/.*var.ext_http_en[[:space:]]*=[[:space:]]*"\(.*\)".*/\1/p' $CONF_LIGHTY)
 
-	if ! test -e $LIGHTY_PEM; then
-		ln $BOX_PEM $LIGHTY_PEM
+	https_port=$(sed -n 's/^var.https_port[[:space:]]*=[[:space:]]*\([[:digit:]]*\).*/\1/p' $CONF_LIGHTY)
+	ext_https_port=$(sed -n 's/^var.ext_https_port[[:space:]]*=[[:space:]]*\([[:digit:]]*\).*/\1/p' $CONF_LIGHTY)
+	ext_https_en=$(sed -n 's/.*var.ext_https_en[[:space:]]*=[[:space:]]*"\(.*\)".*/\1/p' $CONF_LIGHTY)
+}
+
+# $1-enable $2-external, $3-internal $4-desc
+open_port() {
+	if test "$1" = "yes" -a -n "$2" -a -n "$3" -a -n "$4"; then
+		# ip port external_port protocol
+		upnpcc -e "$4" -a $(hostname -i) $3 $2 TCP > /dev/null
 	fi
+}
+
+# $1-port
+close_port() {
+	if test -n "$1"; then
+		upnpcc -d $1 TCP > /dev/null
+	fi
+}
+
+open_router_ports() {
+	router_ports	
+	open_port $ext_http_en $ext_http_port $http_port "Alt-F lighttpd (HTTP)"
+	open_port $ext_https_en $ext_https_port $https_port "Alt-F lighttpd (HTTPS)"
+}
+
+# FIXME: If config is changed after ports are open, can't close them. Can't fix
+close_router_ports() {
+	router_ports
+	close_port $ext_http_port
+	close_port $ext_https_port
+}
+
+check() {
+	echo
+	status $NAME
+	st=$?
+	echo
+	
+	ext_ip=$(upnpcc -s | sed -n 's/^ExternalIPAddress = \(.*\)/\1/p')
+	ext_domain=$(nslookup $ext_ip | awk '/^Address.*'$ext_ip'/{print $4}');
+	if test -n "$ext_domain"; then
+		emsg="assigned do DNS host \"${ext_domain}\"."
+	else
+		emsg="not DNS assigned!"
+	fi
+	echo -e "External IP: \"$ext_ip\" $emsg\n"
+	
+	router_ports
+	echo "Router forwarded ports:"
+	upnpcc -l | grep -- '->'
+
+	if test "$st" = 0; then
+		echo -e "\nInternet accessible ports:"
+		canyouseeme $ext_http_port
+		st=$((st+$?))
+		canyouseeme $ext_https_port
+		st=$((st+$?))
+	fi
+	
+	return $st
 }
 
 case "$1" in
-	init) istart ;;
 	start)
-		istart
-		start $NAME -- -f $CONFF
+		open_router_ports
+		cron add "$(date +"%M %k") * * *" "$CRON_CMD"
+		start $NAME -- -f $CONF_LIGHTY
 		;;
-	stop) stop $NAME ;;
-	status)	status $NAME ;;
+	stop) # stop server and close ports
+		stop $NAME
+		cron remove "$CRON_CMD"
+		close_router_ports
+		;;
+	sstop) stop $NAME ;; # stop only server
+	status) status $NAME ;;
+	check) check ;;
+	openports) open_router_ports ;;
+	closeports) close_router_ports ;;
 	restart) restart $NAME ;;
-	*) usage $0 "start|stop|status|restart|init" ;;
+	*) usage $0 "start|stop|sstop|status|restart|check|init|openports|closeports" ;;
 esac
 
diff --git a/alt-f/customroot/etc/init.d/common b/alt-f/customroot/etc/init.d/common
--- a/alt-f/customroot/etc/init.d/common
+++ b/alt-f/customroot/etc/init.d/common
@@ -1,5 +1,16 @@
 #set -x
 
+omsg() {
+	if test $1 = 0; then
+		echo "OK."
+	elif test -n "$2"; then
+		echo -e "Fail: $2"
+	else
+		echo "Fail."
+	fi
+	return $1	
+}
+
 # Add "enable" and "disable" options for all scripts.
 # Notice that scripts which set 'umask 077' and are all or group executable
 # can't be boot disabled by the webUI.
@@ -25,6 +36,17 @@ Use menu Packages->Alt-F to install Alt-F packages folder if you have not yet do
 	fi
 fi
 
+if test "$1" = "init"; then
+	if a=$(type sinit) && test "$a" = "sinit is a shell function"; then
+		echo -n "Initializing $(basename $0): "
+		sinit
+		omsg $?
+	else
+		omsg 1 "no sinit() function in $(basename $0)"
+	fi
+	exit
+fi
+
 # for process match, some processes need -n, the default, others -x
 if test -z "$RC_START_STOP"; then
 	RC_START_STOP=-n
@@ -43,21 +65,78 @@ AVAHI_SRV_DIR=/etc/avahi/services
 
 # $1-add/remove $2-service name
 avahi() {
-	if ! test -d $AVAHI_SRV_DIR; then return 0; fi
+	if test -z "$(ls -A $AVAHI_SRV_DIR 2> /dev/null)"; then return 0; fi
  
 	stype=$(sed -n "s|.*<type>\(.*$2.*\)</type>|\1|p" $AVAHI_SRV_DIR/$2.service* 2> /dev/null)
 	
-	for i in $(grep -l "<type>$stype</type>" $AVAHI_SRV_DIR/*.service*); do
+	for i in $(grep -l "<type>$stype</type>" $AVAHI_SRV_DIR/*.service* 2> /dev/null); do
 		sext=${i##*.}
 		sname=$(basename $i)
 		sname=${sname%%.*}
 		
 		if test "$1" = "add" -a "$sext" = "service-"; then
-				mv $AVAHI_SRV_DIR/$sname.service- $AVAHI_SRV_DIR/$sname.service
+			mv $AVAHI_SRV_DIR/$sname.service- $AVAHI_SRV_DIR/$sname.service
 		elif test "$1" = "remove" -a "$sext" = "service"; then
-				mv $AVAHI_SRV_DIR/$sname.service $AVAHI_SRV_DIR/$sname.service-
+			mv $AVAHI_SRV_DIR/$sname.service $AVAHI_SRV_DIR/$sname.service-
 		fi
 	done
+}
+
+CRONF=/var/spool/cron/crontabs/root
+
+# $1-add/remove/status [$2-"cron specs"] $3-"CMD args" 
+cron() {
+	if test $# = 3; then cmd="$3"; else cmd="$2"; fi
+	
+	if test "$1" = "add"; then
+		TF=$(mktemp -t)
+		crontab -l > $TF 2> /dev/null
+		sed -i "\|$cmd.*#!# Alt-F cron$|d" $TF
+		if test $# = 3; then
+			tspec="$2"
+		else # once a week
+			dt=$RANDOM
+			min=$((dt % 60))
+			hour=$((dt % 24))
+			wday=$((dt % 7))
+			tspec="$min $hour * * $wday"		
+		fi
+		
+		echo "$tspec $cmd #!# Alt-F cron" >> $TF
+		touch -r $CRONF $TF
+		crontab $TF 2> /dev/null
+		touch -r $TF $CRONF
+		rm $TF
+		if ! rccron status >& /dev/null; then
+			rccron start # required to handle crontabs
+		fi
+	
+	elif test "$1" = "remove"; then
+		TF=$(mktemp -t)
+		crontab -l > $TF 2> /dev/null
+		sed -i "\|$2.*#!# Alt-F cron$|d" $TF
+		touch -r $CRONF $TF
+		crontab $TF 2> /dev/null
+		touch -r $TF $CRONF
+		rm $TF
+		if ! test -s $CRONF; then
+			rccron stop # no crontab, cron not required
+		fi
+
+		
+	elif test "$1" = "status"; then
+		if ! rccron status >& /dev/null; then
+			echo "$NAME stopped"
+			return 1
+		elif crontab -l 2>/dev/null | grep -q "$2.*#!# Alt-F cron$"; then
+			rccron start >& /dev/null # required to handle the crontab
+			echo -e "$DESC\n$NAME running"
+			return 0
+		else
+			echo -e "$DESC\n$NAME stopped"
+			return 1
+		fi
+	fi
 }
 
 INETD_CONF=/etc/inetd.conf
@@ -98,7 +177,7 @@ requiredby() {
 			exit 0 # don't stop services that marked themself as 'required'
 		fi
 		if rc$dep status >& /dev/null; then
-			echo \'$srv\' can\'t be stopped, as it is needed by \'$dep\' which is running.
+			echo \'$srv\' can\'t be stopped, it is needed by a running \'$dep\'.
 			exit 1
 		fi
 	done
@@ -136,10 +215,10 @@ status() {
 	fi
 
 	if start-stop-daemon -K -t -q $RC_START_STOP $STOP_ARGS; then
-		echo "$1 running"
+		echo -e "$DESC\n$1 running"
 		return 0
 	else
-		echo "$1 stopped"
+		echo -e "$DESC\n$1 stopped"
 		return 1
 	fi
 }
@@ -154,31 +233,33 @@ dmstatus() {
 		return 1
 	else
 		for i in $dmout; do
-			if test "$(dmsetup info $i | awk '/State/{print $2}')" = "ACTIVE"; then
+			if test "$(dmsetup info $i 2> /dev/null | awk '/State/{print $2}')" = "ACTIVE"; then
 				return 0
 			fi
 		done
 	fi
 }
 
-omsg() {
-	if test $1 = 0; then
-		echo "OK."
-	elif test -n "$2"; then
-		echo -e "Fail: $2"
-	else
-		echo "Fail."
-	fi
-	return $1	
-}
+#omsg() {
+#	if test $1 = 0; then
+#		echo "OK."
+#	elif test -n "$2"; then
+#		echo -e "Fail: $2"
+#	else
+#		echo "Fail."
+#	fi
+#	return $1	
+#}
 
 # some services need to create its own user/group
 check_user() {
 	if test -n "$RC_USER" -a -n "$RC_USERN" -a -n "$RC_GROUP" -a -n "$RC_GROUPN" -a -n "$RC_DESC"; then
 		srva=$(basename $0); srv=${srva:3}
 		user_home=/var/lib/$RC_USER
-		if ! id $RC_USER >& /dev/null; then
+		if ! grep -q ^$RC_GROUP:x:$RC_GROUPN: /etc/group; then
 			addgroup -S -g $RC_GROUPN $RC_GROUP >& /dev/null
+		fi
+		if ! id $RC_USER >& /dev/null; then
 			adduser -S -g "$RC_DESC" -G $RC_GROUP -u $RC_USERN -h $user_home $RC_USER >& /dev/null
 		fi
 		if ! test -d $user_home; then
@@ -207,13 +288,18 @@ start() {
 		fi
 	fi
 
-	echo -n "Starting $(basename $1): "
-	if test -n "$RC_START_CMD"; then
-		$RC_START_CMD
-	else
-		start-stop-daemon -S -q -o $RC_START_BG $ARGS_PID -x $*
+	exe=$(basename $1)
+	echo -n "Starting $exe: "
+	which $exe >& /dev/null; st=$?
+	if test $st = 0; then
+		if test -n "$RC_START_CMD"; then
+			$RC_START_CMD
+		else
+			start-stop-daemon -S -q -o $RC_START_BG $ARGS_PID -x $*
+		fi
+		st=$?
 	fi
-	omsg $?
+	omsg $st
 }
 
 stop() {
@@ -263,7 +349,7 @@ stop() {
 
 restart() {
 	echo "Restarting $(basename $1): "
-	sh $0 stop
+	if ! sh $0 stop; then exit 1; fi
 
 	STOP_ARGS="$1"
 	if test -n "$RC_PIDFILE"; then
@@ -288,6 +374,6 @@ reload() {
 }
 
 usage() {
-	echo "Usage: $1 {$2}"
+	echo -e "$DESC\nUsage: $1 {$2}"
 	exit 1
 }
diff --git a/alt-f/customroot/etc/init.d/rcS b/alt-f/customroot/etc/init.d/rcS
--- a/alt-f/customroot/etc/init.d/rcS
+++ b/alt-f/customroot/etc/init.d/rcS
@@ -2,20 +2,32 @@
 
 #set -x
 
+TSYSLOG=/var/log/boot.log
+SERRORL=/var/log/systemerror.log
+
+UBIROOT=/rootmnt/ubiimage
+SQROOT=/rootmnt/sqimage
+
 mount -t proc proc /proc
 mount -o remount,rw /
 mount -t sysfs sysfs /sys
 mount -t tmpfs tmpfs /tmp
+mount -t devtmpfs devtmpfs /dev 
 
-#mount -t devtmpfs devtmpfs /dev
-#mount -t tmpfs tmpfs /dev
-#mknod /dev/null c 1 3
+# overlayfs (not used) seems to need tmpfs on /dev?
+#mount -t tmpfs tmpfs /dev 
+#mknod /dev/null c 1 3  
 #mknod /dev/console c 5 1
-#mkdir /dev/pts
-/bin/mount -t devpts devpts /dev/pts
 
+mkdir -p /dev/pts
+mount -t devpts devpts /dev/pts
+
+# pre-init cleanup
 rmdir /newroot/rootmnt /newroot >& /dev/null
+umount /boot >& /dev/null
+freeramdisk /dev/ram0 >& /dev/null
 
+# setup tmp dirs in /tmp
 for i in lib run log cache spool db lock; do
 	mkdir -p /tmp/$i
 	ln -sf /tmp/$i /var/$i
@@ -27,26 +39,35 @@ chmod a+wt /var/spool/lpd /var/spool/samba
 echo > /etc/bay
 echo -n > /etc/printcap
 
+touch /var/log/wtmp /var/run/utmp
+chown root:utmp /var/log/wtmp /var/run/utmp
+chmod 664 /var/log/wtmp /var/run/utmp
+
 # bootlog. syslog has not yet started, and hot.sh uses "logger",
-TSYSLOG=/var/log/boot.log
 start-stop-daemon -S -q -x syslogd -- -m 0 -D -S -O $TSYSLOG
+
+# There is a lack of entropy to generate private keys or do other SSL operations.
+# Use haveged to collect entropy. Kill it at this script end and let init respawn it.
+haveged -r0
 
 # what box/board?
 mkdir -p /tmp/sys
 
-if grep -q 'ARM-Versatile PB' /proc/cpuinfo; then
-	board="qemu"
-elif grep -q 'DNS-321/323' /proc/cpuinfo; then
+if grep -q 'DNS-321/323' /proc/cpuinfo; then
 	case $(sed -n 's/Revision.*:.\([[:digit:]]*\).*/\1/p' /proc/cpuinfo) in
 		0000) board="DNS-323-A1" ;;
 		0001) board="DNS-323-B1" ;;
 		0002) board="DNS-323-C1" ;;
 		0003) board="DNS-321-Ax" ;; 
 	esac
+elif grep -q 'ARM Versatile PB' /proc/device-tree/model 2> /dev/null; then
+	board="qemu"
 elif grep -q 'DNS-320L-rev-Ax' /proc/device-tree/model 2> /dev/null; then
 	board="DNS-320L-Ax"
 elif grep -q 'DNS-320-rev-Ax' /proc/device-tree/model 2> /dev/null; then
 	board="DNS-320-Ax"
+elif grep -q 'DNR-322L-rev-Ax' /proc/device-tree/model 2> /dev/null; then
+	board="DNR-322L-Ax"
 elif grep -q 'DNS-320-rev-Bx' /proc/device-tree/model 2> /dev/null; then
 	board="DNS-320-Bx"
 elif grep -q 'DNS-325-rev-Ax' /proc/device-tree/model 2> /dev/null; then
@@ -61,25 +82,23 @@ echo $board > /tmp/board
 chmod -w /tmp/board
 
 if echo $board | grep -qE "qemu"; then
-	config_mtd=/dev/mtdblock0; config_mn="31 0"
 	mkdir -p /tmp/sys/power_led
 	sed -i 's/ttyS0/ttyAMA0/g' /etc/inittab
 	kill -1 1
-elif echo $board | grep -qE "DNS-321|DNS-323"; then
-	kernel_mtd=/dev/mtd2; kernel_mn="90 4"
-	config_mtd=/dev/mtdblock0; config_mn="31 0"
 	
+elif echo $board | grep -qE "DNS-321|DNS-323"; then
+	kernel_mtd=/dev/mtd2
+
 	ln -sf "/sys/class/leds/power:blue" /tmp/sys/power_led
 	ln -sf "/sys/class/leds/left:amber" /tmp/sys/left_led
 	ln -sf "/sys/class/leds/right:amber" /tmp/sys/right_led
 
-elif echo $board | grep -qE "DNS-320|DNS-325|DNS-327L"; then
-	kernel_mtd=/dev/mtd1; kernel_mn="90 2"
-	config_mtd=/dev/mtdblock5; config_mn="31 5"
+elif echo $board | grep -qE "DNR-322L|DNS-320|DNS-325|DNS-327L"; then
+	kernel_mtd=/dev/mtd1
 
 	# Tell PMU to turn back on after a power failure
 	# From http://jamie.lentin.co.uk/devices/dlink-dns325/userland-configuration/
-	if test $board = "DNS-320-Ax" -o $board = "DNS-325-Ax"; then
+	if test $board = "DNR-322L-Ax" -o $board = "DNS-320-Ax" -o $board = "DNS-325-Ax"; then
 		echo 37 > /sys/class/gpio/export
 		echo out > /sys/class/gpio/gpio37/direction
 		echo 1 > /sys/class/gpio/gpio37/value
@@ -87,8 +106,10 @@ elif echo $board | grep -qE "DNS-320|DNS-325|DNS-327L"; then
 	fi
 
 	# MAC is stored in /dev/mtd4, configure eth0
-	if ! test -e /dev/mtd4; then mknod /dev/mtd4 c 90 8; fi
-	ifconfig eth0 hw ether $(nanddump -ql 2048 /dev/mtd4 | grep -E '..(:..){5}')
+	IFMAC=$(nanddump -ql 2048 /dev/mtd4 | grep -oE '[[:xdigit:]]{2}(:[[:xdigit:]]{2}){5}')
+	if test -n "$IFMAC"; then
+		ifconfig eth0 hw ether $IFMAC
+	fi
 
 	# get sqimage from tftp if bootargs contains tftpargs=myip:tftpip[:netmask]
 	tftpargs=$(sed -n 's/.*tftpargs=\([.:[:digit:]]*\).*/\1/p' /proc/cmdline)
@@ -97,36 +118,41 @@ elif echo $board | grep -qE "DNS-320|DNS-325|DNS-327L"; then
 		if echo $board | grep -q DNS-327L; then aboard="dns327"; fi
 
 		eval $(echo $tftpargs | awk -F: '{printf "myip=%s tftpip=%s netmsk=%s", $1, $2, $3}')
-		logger -st rcS "tftp getting sqimage from $tftpip, myip $myip"
+		logger -st rcS "tftp getting sqimage-$aboard from $tftpip, myip $myip"
 		ifconfig eth0 up $myip netmask ${netmsk:-255.255.255.0}
-		if ! tftp -g -r rootfs.arm.sqimage.xz-$aboard -l /tmp/sqimage.xz $tftpip; then
+		if ! tftp -g -r sqimage-$aboard -l /tmp/sqimage.xz $tftpip; then
 			logger -st rcS "tftp get failed"
+		else
+			logger -st rcS "loop aufs mount sqimage-$aboard"
+			chmod -w /tmp/sqimage.xz
+			mkdir -p $SQROOT
+			mount -o loop /tmp/sqimage.xz $SQROOT
+			mount -t aufs -o remount,append:${SQROOT}=rr /		
 		fi
 		ifconfig eth0 down
-	else # get squashfs image from NAND
-		# can't be run from a NAND (dns-320/325/327), in contrast to a NOR (dns-323/321)
-		# FIXME: create a 100MB ubifs on mtd3 and run the rootfs from it
-		if ! test -e /dev/mtd3; then mknod /dev/mtd3 c 90 6; fi
-		eval $(nanddump -ql 2048 /dev/mtd3 | strings) # contains sqimage_size=bytes_of_sqimage;
-		if test -n "$sqimage_size"; then
-			if test "$sqimage_size" -gt 0 -a "$sqimage_size" -lt 30000000; then
-				nanddump -qf /tmp/sqimage.xz -s 2048 -l $sqimage_size /dev/mtd3
+	fi
+	
+	if ubiattach -d 1 -p /dev/mtd3 -O 2048; then # ubi/ubifs setup
+		mkdir -p $UBIROOT
+		if mount -t ubifs -o rw /dev/ubi1_0 $UBIROOT; then
+			sync
+			if mount -t squashfs | grep -q /rootmnt/sqimage; then
+				#mount at bottom, as ubiimage might contain outdated pkgs
+				mount -t aufs -o remount,append:${UBIROOT}=ro /
+			else
+				# insert where /rootmnt/ro currently is; ro will be keept at bottom
+				ix=$(basename $(grep -l /rootmnt/ro /sys/fs/aufs/*/br?))
+				mount -t aufs -o remount,ins:${ix#br}:${UBIROOT}=ro /
 			fi
+		else
+			ubidetach -p /dev/mtd3
+			logger -st rcS "UBIFS mount failed"
 		fi
+	else
+		logger -st rcS "UBI attach failed, minimum system loaded."
 	fi
 
-	# loop/aufs mount sqimage
-	if test -s /tmp/sqimage.xz; then
-		chmod -w /tmp/sqimage.xz
-		mkdir -p /rootmnt/sqimage
-		mount -o loop /tmp/sqimage.xz /rootmnt/sqimage
-		mount -t aufs -o remount,append:/rootmnt/sqimage=rr /
-	fi
-
-	# the dns320-temp.sh/dns320l-daemon needs ttyS1, not yet available
-	if ! test -e /dev/ttyS1; then mknod /dev/ttyS1 c 4 65; fi
-
-	if test $board = "DNS-320-Ax"; then
+	if test $board = "DNS-320-Ax" -o $board = "DNR-322L-Ax" ; then
 		ln -sf "/sys/class/leds/dns320:blue:power" /tmp/sys/power_led
 		ln -sf "/sys/class/leds/dns320:orange:l_hdd" /tmp/sys/left_led
 		ln -sf "/sys/class/leds/dns320:orange:r_hdd" /tmp/sys/right_led
@@ -150,8 +176,7 @@ elif echo $board | grep -qE "DNS-320|DNS-325|DNS-327L"; then
 		fi
 		ln -sf /sys/class/gpio/gpio29/value /tmp/sys/power_button
 		mkdir -p /tmp/sys/power_led
-		echo none > /tmp/sys/power_led/trigger
-		echo 1 > /tmp/sys/power_led/brightness
+
 		echo 0 > /tmp/sys/usb2_led/brightness
 		echo 0 > /tmp/sys/fan1_input
 
@@ -171,7 +196,7 @@ elif echo $board | grep -qE "DNS-320|DNS-325|DNS-327L"; then
 		ln -sf "/sys/class/leds/dns327l:amber:sata-r" /tmp/sys/right_led
 		ln -sf "/sys/class/leds/dns327l:white:usb" /tmp/sys/usb2_led
 		
-		if ! test -f /sys/class/gpio/gpio65/value; then # power button don't generate interrup!
+		if ! test -f /sys/class/gpio/gpio65/value; then # power button don't generate interrupt!
 			echo 65 > /sys/class/gpio/export
 			echo out > /sys/class/gpio/gpio65/direction # sigh...
 			echo in > /sys/class/gpio/gpio65/direction # sigh...
@@ -180,19 +205,12 @@ elif echo $board | grep -qE "DNS-320|DNS-325|DNS-327L"; then
 
 		ln -sf /sys/class/hwmon/hwmon0/temp1_input /tmp/sys/cpu_temp
 		mkdir -p /tmp/sys/power_led
-		echo none > /tmp/sys/power_led/trigger
-		echo 1 > /tmp/sys/power_led/brightness
+
 		echo 0 > /tmp/sys/usb2_led/brightness
 		echo 0 > /tmp/sys/fan1_input
 		echo 0 > /tmp/sys/temp1_input
 
 		# attach mtd5 (settings) to ubi0, for loadsave_settings
-		if ! test -e /dev/mtd5; then
-			mknod /dev/mtd5 c 90 10
-			mknod /dev/ubi_ctrl c 10 59
-			mknod /dev/ubi0 c 252 0
-			mknod /dev/ubi0_0 c 252 1
-		fi
 		ubiattach -p /dev/mtd5 -d 0
 
 		# make init launch dns320l-daemon
@@ -202,9 +220,6 @@ elif echo $board | grep -qE "DNS-320|DNS-325|DNS-327L"; then
 fi
 
 if test "$board" != "Unknown"; then
-	if ! test -e $kernel_mtd; then mknod $kernel_mtd c $kernel_mn; fi
-	if ! test -e $config_mtd; then mknod $config_mtd b $config_mn; fi
-
 	for i in fan1_input temp1_input pwm1; do
 		j=$(find /sys/class/ -follow -maxdepth 4 -name $i)
 		if test -n "$j" -a ! -f /tmp/sys/$i; then
@@ -224,7 +239,6 @@ fi
 
 # notice, settings not yet loaded, TZ set to NONE-0
 logger -st rcS "Reading RCT in UTC and setting system time and date"
-if ! test -e /dev/rtc0; then mknod /dev/rtc0 c 254 0; fi
 hwclock -su
 
 logger -st rcS "Board: $board"
@@ -238,8 +252,8 @@ if ! grep -q "nodef" /proc/cmdline; then
 	logger -st rcS "$res"
 	
 	if loadsave_settings -gb; then
-		touch /tmp/fsckboot
 		logger -st rcS "Forcing fsck at boot"
+		touch /tmp/fsckboot
 	fi
 
 	if test -s /etc/misc.conf; then
@@ -248,9 +262,9 @@ if ! grep -q "nodef" /proc/cmdline; then
 fi
 
 # rsyncd.secrets can be in sqimage
-if test -f /etc/rsyncd.secrets; then
-	chmod og-r /etc/rsyncd.secrets
-fi
+#if test -f /etc/rsyncd.secrets; then
+#	chmod og-r /etc/rsyncd.secrets
+#fi
 
 # create lock file for aufs.sh synchronization, minimizing (not solving!) hotpluging
 # interation issues with initscripts when /Alt-F is mounted
@@ -259,10 +273,29 @@ while ! mkdir $aufslock >& /dev/null; do usleep 500000; done
 
 # sequence hotplug events
 echo > /dev/mdev.seq 
+
+# "hotplug", mdev.conf calls /usr/sbin/hot.sh, 
+echo /sbin/mdev > /proc/sys/kernel/hotplug
+
 # populate /dev
 /sbin/mdev -s
-# "hotplug", mdev.conf registers /usr/sbin/hot.sh, 
-echo /sbin/mdev > /proc/sys/kernel/hotplug
+
+# stolen from https://github.com/slashbeast/mdev-like-a-boss/blob/master/mdev.init
+# mdev -s does not poke network interfaces or usb devices so we need to do it here.
+# for i in /sys/class/net/*/uevent; do printf 'add' > "$i"; done 2>/dev/null; unset i
+# for i in /sys/bus/usb/devices/*; do
+# 	case "${i##*/}" in
+# 		[0-9]*-[0-9]*)
+# 			printf 'add' > "$i/uevent"
+# 		;;
+# 	esac
+# done
+#
+# Load kernel modules, run twice.
+# find /sys -name 'modalias' -type f -exec cat '{}' + | sort -u | xargs modprobe -b -a 2>/dev/null
+# find /sys -name 'modalias' -type f -exec cat '{}' + | sort -u | xargs modprobe -b -a 2>/dev/null
+# end of stolen
+# all the above could be avoided if we just modprobe usb-storage... use /etc/modules for that instead?
 
 # set a default hostname based on box model and network MAC
 if ! test -s /etc/hostname; then
@@ -281,7 +314,7 @@ hostname -F /etc/hostname
 # 4th, try to use a dhcp server
 # 5th, find and use a non-used ip address from 192.168.1.254 to 230 range
 if grep -q "ip=" /proc/cmdline; then
-	logger -st rcS "IP from kernel cmdline, kernel brings eth0 up"
+	logger -st rcS "IP from kernel cmdline"
 	cip="kip"
 	eval $(cat /proc/cmdline)
 	ns=$(echo $ip | awk -F: '{ print $3 }')
@@ -296,7 +329,9 @@ if grep -q "ip=" /proc/cmdline; then
 	fi
 	ifconfig eth0 up
 elif test $no_defaults = "0"; then
-	logger -st rcS "IP from flash-defaults"
+	ipt=$(sed -n 's/iface.*eth0.*inet\(.*\)/\1/p' /etc/network/interfaces)
+	ips=$(sed -n 's/address\(.*\)/\1/p' /etc/network/interfaces)
+	logger -st rcS "IP from flash-defaults:$ipt $ips"
 	cip="def"
 	ifup eth0
 else
@@ -403,7 +438,14 @@ case $cip in
 		;;
 esac
 
+# load specified but not autoloading modules
+if grep -qv "# list of modules" /etc/modules; then
+	logger -st rcS "Loading kernel modules"
+	modprobe -avb $(sed 's/#.*//' /etc/modules | tr -s '\n' ' ')
+fi
+
 # configure kernel parameters
+logger -st rcS "Setting kernel parameters"
 sysctl -p
 
 # create rc* shortcuts to /etc/init.d/S??*
@@ -416,14 +458,21 @@ done
 # stop temporary syslog to /var/log/boot.log
 start-stop-daemon -K -q -n syslogd
 
-# execute rc.sys, which is saved on flash and might contain short system fixes
+# execute rc.sys, which is saved on flash and might contain small system fixes
 if test -x /etc/init.d/rc.sys; then
 	logger -st rcS "Executing rc.sys"
 	/etc/init.d/rc.sys
 fi
 
+# set time from ntp server, RTC may have drifted or its battery exhausted
+fsntp -s
+
 # Start all executable init scripts
+rcall init
 rcall start
+
+# kill early launched haveged, let init respawn it
+kill $(cat /var/run/haveged.pid)
 
 # remove aufs.sh lock
 rmdir $aufslock
diff --git a/alt-f/customroot/usr/bin/backup b/alt-f/customroot/usr/bin/backup
--- a/alt-f/customroot/usr/bin/backup
+++ b/alt-f/customroot/usr/bin/backup
@@ -1,34 +1,63 @@
 #!/bin/sh
 
-exec >> /var/log/backup.log 2>&1
-#set -x
-echo -e "\nDATE=$(date)"
-
 # backup.conf
 # structure for type=dir, when/at should be crontab compatible, at least for now
 #id;type;runas;host;mac;srcdir;dstdir;when;at;log;nlogs
 
+CONF_M=/etc/misc.conf
 CONF_BACKUP=/etc/backup.conf
 SERRORL=/var/log/systemerror.log
 
-lockfile=/var/lock/backup.lockdir
+LOCKFILE=/var/lock/backup.lockdir
+LOGFILE=/var/log/backup.log
+PIDFILE=/var/run/backup.pid
+STATEFILE=/tmp/backup-state.
+
+#set -x
+
+error() {
+	logger -st backup "$1"
+	if test -n "$BACKUP_LOG"; then
+		echo "<li>Error on Backup ID $id: $1</li>" >> $SERRORL
+		echo "$1" | mail -s "Error on backup ID $id on host $host" -a $destname/${date}.log $MAILTO
+	fi
+}
+
+cleanup() {
+	logger -st backup "$1"
+	if test "$2" != 0; then
+		ERR="Error on"
+	fi
+
+	if test -n "$BACKUP_LOG"; then
+		ln=$(grep -n DATE= $LOGFILE | tail -1 | cut -d: -f1)
+		sed -n $ln,\$p $LOGFILE | \
+		mail -s "$ERR Backup log of $save_srcpath on $host at ${date-$(date)}" -a $destname/${date}.log $MAILTO
+	fi
+
+	lock
+	rm -f $PIDFILE ${STATEFILE}$id
+	unlock
+
+	exit $2
+}
 
 lock() {
-	while ! mkdir $lockfile >& /dev/null; do
+	while ! mkdir $LOCKFILE >& /dev/null; do
 		sleep 5
 	done
 }
 
 unlock() {
-	rmdir $lockfile >& /dev/null
+	rmdir $LOCKFILE >& /dev/null
 }
 
 exclusive() {
 	lock
-	while test -e /var/run/backup.pid; do
-		if kill -0 $(cat /var/run/backup.pid) >& /dev/null; then
+	while test -e $PIDFILE; do
+		if kill -0 $(cat $PIDFILE) >& /dev/null; then
 			# logger -st backup "backup $id waiting a minute, other backup is occurring."
-			echo "Queued" > /tmp/backup-state.$id
+			echo "Queued" > ${STATEFILE}$id
 			unlock
 			sleep 60
 			lock
@@ -37,23 +66,9 @@ exclusive() {
 		fi
 	done
 
-	echo $$ > /var/run/backup.pid
-	echo "In progress" > /tmp/backup-state.$id
+	echo $$ > $PIDFILE
+	echo "In progress" > ${STATEFILE}$id
 	unlock
-}
-
-# $1=id
-details() {
-	IFS=";"
-	while read id type runas host mac srcpath dstpath when at log nlogs rest; do
-		if test -z "$id" -o -z "$type" -o -z "$runas" -o -z "$srcpath" -o -z "$dstpath" \
-			-o -z "$when" -o -z "$at" -o -z "$log" -o -z "$nlogs"; then continue; fi
-		if test "${id:0:1}" = "#"; then continue; fi
-		if test "$1" = "$id"; then return 0; fi
-#echo $id $type $runas $host $mac $srcpath $dstpath $when $at $log +$nlogs+ -$rest-
-	done < $CONF_BACKUP 
-
-	return 1
 }
 
 clean_logs() {
@@ -61,7 +76,7 @@ clean_logs() {
 	while test "$((clogs - 1))" -gt "$nlogs"; do
 		clogs=$((clogs-1))
 		last=$(ls $ddname | grep '^....-..-.._..-..-..$' | head -1)
-		logger -st backup "backup $id with $clogs backups ($nlogs configured), removing oldest $last"
+		logger -st backup "Backup $id with $clogs backups ($nlogs configured), removing oldest $last"
 		rm -rf "$last" "${last}.log" 
 	done
 }
@@ -79,7 +94,7 @@ wakeup() {
 	ether-wake $mac
 
 	for i in 1 2 3 4 5; do
-		sleep 30
+		sleep 60
 		if ping -W 3 -c 2 $host >& /dev/null; then
 			logger -st backup "ID $id: $host is awake"
 			return 0
@@ -92,11 +107,12 @@ wakeup() {
 }
 
 # For log format see rsync man page: --itemize-changes. Essentially
+# >f+++++++++ file' mean a new file
 # >f.s....... file' means file was updated due to size change
 # >f..t...... file' means file was updated due to time change
-# >f+++++++++ file' mean a new file
-# cd..tpog... dir' means a created dir
 # .f..xxx  file' means no file content change, only xxx attributes
+#
+# cd..tpog... dir' means a created dir
 # .d..xxx  dir' means no dir change, only xxx attributes
 #
 # srcpath - from, destname - to
@@ -107,28 +123,48 @@ do_backup() {
 	chown ${runas}:${gid} $destname
 	chown ${runas}:${gid} $destname/$date
 
+	# rsync errors
+	err_1="Syntax or usage error"
+	err_2="Protocol incompatibility"
+	err_3="Errors selecting input/output files, dirs"
+	err_4="Requested action not supported: an attempt was made to manipulate
+	64-bit files on a platform that cannot support them; or an option
+	was  specified  that  is  supported  by the client and not by the
+	server"
+	err_5="Error starting client-server protocol"
+	err_6="Daemon unable to append to log-file"
+	err_10="Error in socket I/O"
+	err_11="Error in file I/O"
+	err_12="Error in rsync protocol data stream"
+	err_13="Errors with program diagnostics"
+	err_14="Error in IPC code"
+	err_20="Received SIGUSR1 or SIGINT"
+	err_21="Some error returned by waitpid()"
+	err_22="Error allocating core memory buffers"
+	err_23="Partial transfer due to error"
+	err_24="Partial transfer due to vanished source files"
+	err_25="The --max-delete limit stopped deletions"
+	err_30="Timeout in data send/receive"
+	err_35="Timeout waiting for daemon connection"
+	
 	if test $type = "rsync" -o -e "$destname/current"; then
-		rsync_opt="$rsync_pass --link-dest=$destname/current"
-	else
-		first_time=1
-	fi
-
-	if test -z "$first_time"; then
-		# the '/' in "$srcpath" is to copy directory contents, not directory
+		# the trailing '/' in "$srcpath" is to copy folder contents,
+		# not the folder itself
 		res=$(su -c "nice rsync -ax -F --delete-excluded --stats \
-			--log-file=$destname/${date}.log $rsync_opt \
+			--log-file=$destname/${date}.log $rsync_pass \
+			--link-dest=$destname/current \
 			\"${rsync_host}${srcpath}/\" \"$destname/$date\" " ${runas} )
 		st=$?
+		if test $st != 0; then res="($(eval echo \$err_$st)) $res"; fi
 	else
 		res=$(su -c "cd \"$srcpath\"; cp -a ./ \"$destname/$date/\" " ${runas})
 		st=$?
 		if test $st = 0; then res="First backup, all data copied"; fi
 	fi
-
-	if test "$st" != 0; then
-		msg="$id failed but continuing nevertheless, err=$st: $res"
-		logger -st backup "$msg"
-		echo "<li><pre>Backup $msg</pre>" >> $SERRORL
+       
+	if test $st != 0; then 
+		msg="An error occurred, continuing anyway, err=$st $res"
+		error "$msg"
 	fi
 
 	cd $destname
@@ -152,9 +188,8 @@ dir_backup() {
 	fi
 
 	if ! test -d "$srcpath"; then
-		msg="ID $id: $srcpath does not exists, exiting."
-		logger -st backup "$msg"
-		echo "<li><pre>Backup $msg</pre>" >> $SERRORL
+		msg="$srcpath does not exists, exiting."
+		error "$msg"
 		return 1
 	fi
 	
@@ -178,34 +213,33 @@ nfs_mount() {
 }
 
 cifs_mount() {
-	cnt=0
-	while ! smbtree -NbS | grep -qi \\\\$host; do
-		logger -st backup "ID $id: waiting for CIFS on host $host"
-		sleep 10
-		cnt=$((cnt+1))
-		if test "$cnt" = 6; then return 1; fi
-	done
+	#	smbtree this only works for SMB1
 
-	uid=$(id -u $runas); gid=$(id -g $runas)
-	mount -t cifs -o ro,iocharset=utf8,noserverino,credentials=/etc/samba/credentials.$runas,uid=$uid,gid=$gid \
-		"//$host/$srcpath" $mtddir
-	st=$?
-	if test "$st" = 16; then st=0; fi # /etc/mtab issue (linked to /proc/mounts)
-	if test "$st" = 0; then
-		mount -o remount,ro $mtddir # mount.cifs seems to not honour mount '-r' or '-o rp'
-	fi
+	uid=$(id -u $runas); gid=$(id -g $runas); cnt=6
+	while test $cnt != 0; do
+		mount -t cifs -o ro,vers=2.0,iocharset=utf8,noserverino,credentials=/etc/samba/credentials.$runas,uid=$uid,gid=${gid}${altuser} \
+			"//$host/$srcpath" $mtddir
+		st=$?
+		if test "$st" = 32; then
+			altuser=",username=$runas" # a linux box using cifs?
+			echo "Permission denied as user $(awk -F= '/jcard/{print $2}' /etc/samba/smbusers), retrying as user \"$runas\""
+		elif test "$st" = 16; then st=0 # /etc/mtab issue (linked to /proc/mounts)
+		elif test "$st" = 0; then
+			mount -o remount,ro $mtddir # mount.cifs seems to not honour mount '-r' or '-o ro'
+			return $st
+		fi
+		cnt=$((--cnt))
+		sleep 10
+	done
 	return $st
 }
 
 cifs_nfs_backup() {
 	if ! wakeup; then
-		msg="ID $id: host $host not answering, exiting."
-		logger -st backup "$msg"
-		echo "<li><pre>Backup $msg</pre>" >> $SERRORL
+		msg="host $host not answering, exiting."
+		error "$msg"
 		return 1
 	fi
-
-	save_srcpath="$srcpath"
 
 	mtddir=/tmp/backup-$id
 	mkdir -p $mtddir
@@ -224,9 +258,8 @@ cifs_nfs_backup() {
 		st=$?
 		umount $mtddir
 	else
-		msg="ID ${id}: unable to $type mount $host:$save_srcpath, err=$st, exiting."
-		logger -st backup "$msg"
-		echo "<li><pre>Backup $msg</pre>" >> $SERRORL
+		msg="unable to $type mount $host:$save_srcpath, err=$st, exiting."
+		error "$msg"
 	fi
 
 	rmdir $mtddir
@@ -254,11 +287,10 @@ ftp_http_backup() {
 	res=$(su -c "wget -nv -m --no-parent -nH --cut-dirs=$dcnt \
 		-P $destname/mirror $type://$host/${srcpath}/" $runas 2>&1 )
 	st=$?
-	if ! test $st = 0 -o $st = 8; then
+	if ! test $st = 0; then
 		rmdir $destname/mirror $destname
-		msg="ID ${id}: $type://$host/$srcpath failed, err=$st, res:$res"
-		logger -st backup "$msg"
-		echo "<li><pre>Backup $msg</pre>" >> $SERRORL
+		msg="$type://$host/$srcpath failed, err=$st, res:$res"
+		error "$msg"
 		return $st
 	fi
 
@@ -268,9 +300,8 @@ ftp_http_backup() {
 
 rsync_backup() {
 	if ! wakeup; then
-		msg="ID $id: host $host not answering, exiting."
-		logger -st backup "$msg"
-		echo "<li><pre>Backup $msg</pre>" >> $SERRORL
+		msg="host $host not answering, exiting."
+		error "$msg"
 		return 1
 	fi
 
@@ -311,8 +342,7 @@ to host $host. This can't be automated, manual intervention is needed:
 2-Login as user $runas to host $(hostname) and execute the command
 	ssh $host # this will make $(hostname) a trusted host to host $host
 After accepting, you can logout."
-			logger -st backup "ID $id: $msg"
-			echo "<li><pre>Backup ID $id: $msg</pre>" >> $SERRORL
+			error "$msg"
 			echo "$msg" > ${bdir}/../Backup-rsync-ssh.txt
 			chmod a+rw ${bdir}/../Backup-rsync-ssh.txt
 			return 1		
@@ -329,47 +359,77 @@ After accepting, you can logout."
 	return $st
 }
 
-if test "$#" = 0; then
-	logger -st backup "need a backup ID as a argument!"
-	return 1
-fi
+# $1=id
+details() {
+	IFS=";"
+	while read id type runas host mac srcpath dstpath when at log nlogs rest; do
+		if test -z "$id" -o -z "$type" -o -z "$runas" -o -z "$srcpath" -o -z "$dstpath" \
+			-o -z "$when" -o -z "$at" -o -z "$log" -o -z "$nlogs"; then continue; fi
+		if test "${id:0:1}" = "#"; then continue; fi
+		if test "$1" = "$id"; then return 0; fi
+#echo $id $type $runas $host $mac $srcpath $dstpath $when $at $log +$nlogs+ -$rest-
+	done < $CONF_BACKUP 
 
-if ! details "$1"; then
-	logger -st backup "Can't find backup $1 in the configuration file."
 	return 1
-fi
+}
 
-tmp=$(readlink -f $dstpath)
-if ! test -d "$tmp"; then
-	logger -st backup "\"$dstpath\" does not exists or is not a directory"
-	return 1
-fi
+validate() {
+	if test "$#" = 0; then
+		logmsg="Need a backup ID as argument!"
+		return 1
+	fi
 
-while ! mountpoint -q "$tmp"; do
-	tmp=$(dirname "$tmp")
-done
+	if ! details "$1"; then
+		logmsg="Can't find backup ID $1 in configuration file."
+		return 1
+	fi
 
-if test "$tmp" = "/" -o $tmp = "."; then
-	logger -st backup "\"$dstpath\" is not on a mounted filesystem"
-	return 1
+	if ! echo $type | grep -qwE "Dir|NFS|CIFS|FTP|HTTP|rsync"; then
+		logmsg="Type $type not supported."
+		return 1;
+	fi
+	
+	save_srcpath="$srcpath"
+	tmp=$(readlink -f $dstpath)	
+
+	if ! test -d "$tmp"; then
+		logmsg="\"$dstpath\" does not exists or is not a directory."
+		return 1
+	fi
+
+	while ! mountpoint -q "$tmp"; do
+		tmp=$(dirname "$tmp")
+	done
+
+	if test "$tmp" = "/" -o $tmp = "."; then
+		logmsg="\"$dstpath\" is not on a mounted filesystem."
+		return 1
+	fi
+	
+	return 0
+}
+
+. $CONF_M
+	
+if ! validate $*; then
+	echo "$logmsg"
+	exit 1
 fi
 
 exclusive
 
-logger -st backup "Doing backup: id=$id type=$type runas=$runas host=$host srcpath=$srcpath \
- dstpath=$dstpath when=$when at=$at log=$log nlogs=$nlogs"
+exec >> $LOGFILE 2>&1
+echo -e "\nDATE=$(date)"
+
+#trap cleanup EXIT
+
+logger -st backup "Doing backup: id=$id type=$type runas=$runas host=$host srcpath=$srcpath dstpath=$dstpath when=$when at=$at log=$log nlogs=$nlogs"
 
 case $type in
 	Dir) dir_backup ;;
 	NFS|CIFS) cifs_nfs_backup ;;
 	FTP|HTTP) ftp_http_backup ;;
 	rsync) rsync_backup ;;
-	*) logger -st backup "type=$type not yet supported" ;;
 esac
-st=$?
 
-lock
-rm /var/run/backup.pid /tmp/backup-state.$id
-unlock
-
-return $st
+cleanup "Exiting" $?
diff --git a/alt-f/customroot/usr/bin/ipkg b/alt-f/customroot/usr/bin/ipkg
--- a/alt-f/customroot/usr/bin/ipkg
+++ b/alt-f/customroot/usr/bin/ipkg
@@ -1,13 +1,19 @@
 #!/bin/sh
 
 CONFF=/etc/ipkg.conf
-IPKG_DIR=/usr/lib/ipkg
+
+IPKG_DIR="/usr/lib/ipkg"
+IPKG_ST="$IPKG_DIR/status"
+
+UBIROOT="/rootmnt/ubiimage"
+UBI_ST="$UBIROOT/$IPKG_ST"
 
 usage() {
 	echo "This is a frontend to ipkg. Use it always!
 Usage:
 	ipkg -install [<mount_point>]
-	ipkg -clean
+	ipkg -clean [root (default) | flash]
+	ipkg -repair [status file]
 	ipkg -update
 	ipkg -help
 	ipkg standard ipkg command"
@@ -23,19 +29,34 @@ msg() {
 	exit 1
 }
 
+# root | flash
 clean() {
-	if ! aufs.sh -s >& /dev/null; then
+	if test "$1" = "root" && ! aufs.sh -s >& /dev/null; then
 		return 0
 	fi
 
 	aufs.sh -n
-	if test -f /usr/bin/ipkg-cl; then
+	if test -x /usr/bin/ipkg-cl; then
 		for i in $(ipkg-cl -V0 list_installed | cut -f1 -d" "); do
+			inst_at=""
+			if grep -q "^Package:[[:space:]]*$i" $UBI_ST >& /dev/null; then
+				inst_at="flash"
+			elif grep -q "^Package:[[:space:]]*$i" $IPKG_ST; then
+				inst_at="root"
+			fi
+			if test "$inst_at" != "$1"; then continue; fi
+		
 			if test "$i" != "ipkg"; then
 				ipkg-cl -force-depends remove $i # >& /dev/null
 			fi
 		done
+		# FIXME: can't remove, flash has packages. change ipkg pkg install
 		ipkg-cl remove ipkg # >& /dev/null
+	fi
+	
+	if test "$1" = "flash"; then
+		aufs.sh -r
+		return 0
 	fi
 
 	if ! aufs.sh -u >& /dev/null; then 
@@ -63,28 +84,18 @@ clean() {
 		if ! aufs.sh -u >& /dev/null; then # no hope
 			echo "ipkg: can't umount aufs branch, exiting."
 			aufs.sh -r
-			rcall start >& /dev/null
+			#rcall start >& /dev/null
 			exit 1
 		fi
-		rcall start >& /dev/null
+		#rcall start >& /dev/null
 	fi
 	
 	rm -rf $(readlink -f /Alt-F) /Alt-F
 }
 
-install() {
-	echo Installing ipkg
-
-	DESTD=$(awk '/^dest/{print $3}' $CONFF)
-
-	if test "$DESTD" != "/Alt-F"; then
-		msg "Package destination directory must be /Alt-F"
-	fi
-
-	if ! test -d "$DESTD"; then
-		msg "Package destination directory not found."
-	fi
-
+download_extract() {
+	echo "Downloading and extracting ipkg"
+	
 	TMPD=$(mktemp -d -t)
 
 	if test -e /tmp/ipkg_*_arm.ipk; then
@@ -144,28 +155,114 @@ and no /tmp/ipkg_*_arm.ipk file found. Exiting"
 	
 	aufs.sh -n
 	tar -C /Alt-F -xzf data.tar.gz
-	mkdir -p /Alt-F/etc/init.d
 	aufs.sh -r
 
 	cd /
 	rm -rf $TMPD
+}
 
+install() {
+	echo Installing ipkg
+
+#	DESTD=$(awk '/^dest.*Alt-F/{print $3}' $CONFF)
+#
+#	if test "$DESTD" != "/Alt-F"; then
+#		msg "Package destination directory must be /Alt-F"
+#	fi
+
+#	if ! test -d "$DESTD"; then
+	if ! test -d "/Alt-F"; then
+		msg "Package destination directory /Alt-F not found."
+	fi
+
+	if ! test -x /usr/bin/ipkg-cl; then
+		download_extract
+	fi
+	
+	aufs.sh -n
+	mkdir -p /Alt-F/etc/init.d /Alt-F/usr/bin /Alt-F/usr/share/ipkg /Alt-F/usr/lib/ipkg/info
+	
+	#mkdir -p $IPKG_DIR
+	if test -s /etc/preinst.status; then
+		cat /etc/preinst.status >> /Alt-F/$IPKG_ST
+	fi
+	aufs.sh -r
+	
 	# "FIXME: remount /Alt-F with inotify bellow makes 3.10.32/3.18.21 crash, the *first* time"
-	mkdir -p /usr/lib/ipkg # this seems to solve the issue. Is it warming-up aufs?
+	#mkdir -p $IPKG_DIR # this seems to solve the issue. Is it warming-up aufs?
 	if test -z "$local"; then
 		aufs.sh -n
 		ipkg-cl update
-		ipkg-cl install ipkg
+#		ipkg-cl install ipkg
 		aufs.sh -r
 	fi
 
-	if test -s /etc/preinst.status; then
-		cat /etc/preinst.status >> $IPKG_DIR/status
-	fi
+#	if test -s /etc/preinst.status; then
+#		cat /etc/preinst.status >> $IPKG_ST
+#	fi
 
 	cat /etc/Alt-F > $IPKG_DIR/.fixed
 
 	exit 0
+}
+
+# remove duplicate pkgs, keeping the higher version one
+repair() {
+	awk '
+	/Package:/ { nm = $2; inst=""; pri=""; dep=""; es=""; cff=""; } # Package is first entry
+	/Conffiles:/ {
+		while (getline) { # getline to $0 means that following rules will be run
+			if (length($0) == 0 || index($0, "./") != 1)
+				break
+			cff = cff "\n" $0
+		}
+	}
+	/Version:/ { ver = $2 }
+	/Depends:/ { dep = substr($0, index($0, ":") + 2) }
+	/Architecture:/ { arc = $2 }
+	/Priority:/ { pri = $2 }
+	/Essential:/ { es = $2 }
+	/Installed-Time:/ { inst = $2 }
+	/Status:/ { st = substr($0, index($0, ":") + 2) }
+	/^$/ {
+		if (nm in pkg) {
+			if (system("ipkg-cl -V0 compare_versions " ver " \"<<\" " pkg[nm]) == 1)
+				next
+		}
+
+		pkg[nm] = ver
+		stat[nm] = st
+		arch[nm] = arc
+		deps[nm] = dep
+		prior[nm] = pri
+		ess[nm] = es
+		instt[nm] = inst
+		conf[nm] = cff
+	}
+	END {
+		for (i in pkg) {
+			printf("Package: %s\n", i)
+			printf("Version: %s\n", pkg[i])
+			if (length(deps[i]))
+				printf("Depends: %s\n", deps[i])
+			if (length(ess[i]))
+				printf("Essential: %s\n", ess[i])
+			printf("Architecture: %s\n", arch[i])
+			if (length(prior[i]))
+				printf("Priority: %s\n", prior[i])
+			printf("Status: %s\n", stat[i])
+			if (length(instt[i]))
+				printf("Installed-Time: %s\n", instt[i])
+			if (length(conf[i]))
+				printf("Conffiles:%s\n", conf[i])
+			printf("\n");
+		}
+	}' $1 > /tmp/po
+	# sort by pkg name
+	for i in $(grep Package: /tmp/po | sort -u | cut -f2 -d" "); do
+		sed -n "/Package: $i$/,/^$/p" /tmp/po
+	done > $IPK_ST
+	rm /tmp/po
 }
 
 # remove installed packages of same or lower version than a existing pre-installed package.
@@ -179,7 +276,7 @@ ipkg_upgrade() {
 	to_save=""
 
 	while read pkg pver; do
-		iver=$(awk '/Package:[[:space:]]*'$pkg'$/{getline; printf $2; exit 0}' $IPKG_DIR/status)
+		iver=$(awk '/Package:[[:space:]]*'$pkg'$/{getline; printf $2; exit 0}' $IPKG_ST)
 		echo $pkg:$pver:$iver:
 		if test -n "$iver" -a -n "$pver"; then
 			# return value from ipkg compare version is reversed,
@@ -221,79 +318,135 @@ ipkg_upgrade() {
 		# backup conf files
 		for i in $to_save; do cp /$i /$i.bck; done
 		aufs.sh -n
-		ipkg-cl -force-depends remove $to_rm
-		ipkg-cl -force-depends remove $to_rm # dooh!
+		# dooh! looks like lists are being rebuild each time and it will eventually work
+		ipkg-cl -force-depends remove $to_rm $to_rm $to_rm
 		aufs.sh -r
 		# restore conf-files 
 		for i in $to_save; do mv /$i.bck /$i; done
 	fi
 
 	if test -s /etc/preinst.status; then
-		cat /etc/preinst.status >> $IPKG_DIR/status
+		cat /etc/preinst.status >> $IPKG_ST
 	fi
 }
 
-if test "$#" != 0 -a "$1" = "-clean"; then
-	clean
+# fix dest
 
-elif test "$#" != 0 -a "$1" = "-install"; then
-	if test $# = 1 -a "$(aufs.sh -s)" != "OK"; then
-		echo "/Alt-F does not exists or is not an aufs branch."
-		echo "you must supply a mountpoint where to install ipkg."
-		exit 1
+# if echo $board | grep -qE "DNR-322L|DNS-320|DNS-325|DNS-327L"; then
+# 	if mount | grep -q $SQROOT; then
+# 		cat /etc/preinst-sq >> /etc/preinst
+# 		cat /etc/preinst-sq.status >> /etc/preinst.status
+# 		cat /etc/preinst-sq.status >> $IPKG_ST
+# 	elif ! mount | grep -q $UBIROOT; then
+# 		echo "<li>UBI failed, minimum system loaded.</li>" >> $SERRORL
+# 	fi
+# fi
 
-	elif test $# = 1 -a "$(aufs.sh -s)" = "OK"; then
-		install
+if ! test -f $IPKG_ST || cmp -s $UBI_ST $IPKG_ST; then
+	mkdir -p $IPKG_DIR
+	cat /etc/preinst.status >> $IPKG_ST
+fi
 
-	elif test $# = 2 -a "$(aufs.sh -s)" = "OK"; then
-		echo "Alt-F already exists, you shouldn't supply a mountpoint."
-		exit 1
+# replace old /Alt-F dest with 'root'
+if grep -q '^dest /Alt-F' $CONFF; then
+	sed -i "s|dest /Alt-F.*$|dest root /|" $CONFF 
+fi
 
-	elif test "$#" != 2; then
-		usage
-	
-	elif ! $(mountpoint -q $2); then
-		echo "\"$2\" is not a mountpoint."
-		exit 1
-
-	else
-		aufs.sh -i $2 && install
-		exit $?
+# adjust ipkg packages destination, depending on UBI
+if mount -t ubifs | grep -qw $UBIROOT; then
+	if ! grep -q '^dest flash' $CONFF; then
+		sed -i "/dest root/a dest flash $UBIROOT" $CONFF
 	fi
+elif grep -q "^dest flash"  $CONFF; then
+	sed -i '/^dest flash/d' $CONFF
+fi
 
-elif test "$#" != 0 -a "$1" = "-update"; then
+# adjust architecture
+arch=$(uname -m); arch=${arch:0:5}
+if ! grep -q '^arch' $CONFF; then
+	echo "arch arm 100" >> $CONFF
+fi
+if ! grep -q "^arch $arch" $CONFF; then
+	echo "arch $arch 200" >> $CONFF
+fi
+
+if test "$1" = "-clean"; then
+	if test $# = "1"; then
+		dest_loc="root"
+	elif test "$2" = "flash"; then
+		dest_loc="flash"
+	elif test "$2" = "root"; then
+		dest_loc="root"
+	else
+		usage
+	fi
+	clean "$dest_loc"
+
+elif test "$1" = "-install"; then
+	
+	if aufs.sh -s; then
+		if test $# != 1; then
+			echo "Alt-F already exists, you shouldn't supply a mountpoint."
+			exit 1
+		else
+			install
+		fi
+	else
+		if test $# != 2; then
+			echo "/Alt-F does not exists or is not an aufs branch."
+			echo "you must supply a mountpoint where to install ipkg."
+			exit 1
+		elif ! mountpoint -q "$2"; then
+			echo "\"$2\" is not a mountpoint."
+			exit 1
+		else
+			aufs.sh -i "$2" && install
+			exit $?
+		fi
+	fi
+	
+elif test "$1" = "-update"; then
 	# this only needs to be done once for a new firmware upgrade
 	if test "$(cat $IPKG_DIR/.fixed 2> /dev/null)" != $(cat /etc/Alt-F) ; then
 		ipkg_upgrade
 		cat /etc/Alt-F > $IPKG_DIR/.fixed
 	fi
 
-elif test "$#" != 0 -a "$1" = "-help"; then
+elif test "$1" = "-repair"; then
+	rpd=$IPKG_ST
+	if test "$2"; then
+		rpd="$2"
+	fi
+	repair $rpd
+	
+elif test "$1" = "-help"; then
 	usage
 
-elif test -f /usr/bin/ipkg-cl; then
+# normal ipkg command
+elif test -f /usr/bin/ipkg-cl; then # && readlink -f /Alt-F >& /dev/null; then
+	
 	# removing a package if it is preinstalled requires ressurrecting/reinstalling it
-	if echo $* | grep -q '[[:space:]]*remove[[:space:]]*'; then
+	if echo $* | grep -qw 'remove'; then
 		pkg=$(eval echo \$$#)   # assume pkg is last command argument
 		# some packages have a rcscript, remake it if it exists
-		if test -f /usr/lib/ipkg/info/$pkg.list && grep -q /etc/init.d/S.* /usr/lib/ipkg/info/$pkg.list; then
-			rclink=$(grep -ho '/sbin/rc.*' /usr/lib/ipkg/info/$pkg.postrm 2> /dev/null)
+		if test -f $IPKG_DIR/info/$pkg.list && grep -q /etc/init.d/S.* $IPKG_DIR/info/$pkg.list; then
+			rclink=$(grep -ho '/sbin/rc.*' $IPKG_DIR/info/$pkg.postrm 2> /dev/null)
 		fi
 	fi
 
 	aufs.sh -n
 	ipkg-cl $*
-	res=$?
+	ret=$?
 	aufs.sh -r
 
 	if test -n "$pkg" -a -f /etc/preinst.status && grep -q "Package:[[:space:]]*$pkg$" /etc/preinst.status; then
 		if test -n "$rclink"; then
 			ln -sf /usr/sbin/rcscript $rclink
 		fi
-		sed -n "/Package: $pkg/,/^$/p" /etc/preinst.status >> /usr/lib/ipkg/status
+		sed -n "/Package: $pkg/,/^$/p" /etc/preinst.status >> $IPKG_ST
 	fi      
 
-	exit $res
+	exit $ret
 
 else
 	usage
diff --git a/alt-f/ipkgfiles/duplicity.postinst b/alt-f/ipkgfiles/duplicity.postinst
--- a/alt-f/ipkgfiles/duplicity.postinst
+++ b/alt-f/ipkgfiles/duplicity.postinst
@@ -1,20 +1,20 @@
 #!/bin/sh
 
-# this is already done at python postinstall script, but because the ipkg order of dependent
-# packages postinstall scripts execution is reversed it needs to be done also here in case
-# python was not previously installed
-
 PVER=2.7
 
 INCDIR=/usr/include/python$PVER
 CONFDIR=/usr/lib/python$PVER/config
 
-PIP_SITE=https://bootstrap.pypa.io
-PIP_SOURCE=get-pip.py
+# PIP_SITE=https://bootstrap.pypa.io
+# PIP_SOURCE=get-pip.py
+# 
+# ELEMT_SITE=http://effbot.org/media/downloads
+# ELEMT_VERSION=1.2.6-20050316
+# ELEMT_TB=elementtree-$ELEMT_VERSION.tar.gz
 
-ELEMT_SITE=http://effbot.org/media/downloads
-ELEMT_VERSION=1.2.6-20050316
-ELEMT_TB=elementtree-$ELEMT_VERSION.tar.gz
+# this is already done at python postinstall script, but because the ipkg order of dependent
+# packages postinstall scripts execution is reversed it needs to be done also here in case
+# python was not previously installed
 
 if ! test -f $INCDIR/pyconfig.h -o -f $CONFDIR/Makefile; then
 	mkdir -p $INCDIR $CONFDIR
@@ -22,24 +22,30 @@ if ! test -f $INCDIR/pyconfig.h -o -f $CONFDIR/Makefile; then
 	mv /usr/lib/python$PVER/Makefile $CONFDIR
 fi
 
-if ! test -f /usr/bin/pip -a -d /usr/lib/python$PVER/site-packages/pip; then
-	echo "Downloading pip... "
-	if ! wget -P /tmp --progress=dot:mega $PIP_SITE/$PIP_SOURCE -P /tmp/; then
-		echo "failed"
-		exit 1
-	fi
-	echo -n "Installing pip, please wait... "
-	if ! python /tmp/$PIP_SOURCE; then
-		echo "failed"
-		exit 1
-	fi
-	rm -f /tmp/$PIP_SOURCE
-fi
+# if ! test -f /usr/bin/pip -a -d /usr/lib/python$PVER/site-packages/pip; then
+# 	echo "Downloading pip... "
+# 	if ! wget -P /tmp --progress=dot:mega $PIP_SITE/$PIP_SOURCE -P /tmp/; then
+# 		echo "failed"
+# 		exit 1
+# 	fi
+# 	echo -n "Installing pip, please wait... "
+# 	if ! python /tmp/$PIP_SOURCE; then
+# 		echo "failed"
+# 		exit 1
+# 	fi
+# 	rm -f /tmp/$PIP_SOURCE
+# fi
 
 # duplicity extra backends
+# dropbox changed api, use 'pip install -I dropbox==6.9.0'
 
-echo "Installing elementtree, lockfile, paramiko, boto, dropbox, gdata, please wait..."
-if ! pip install $ELEMT_SITE/$ELEMT_TB lockfile paramiko boto dropbox gdata; then
+echo "Installing future, fasteners, paramiko, boto, dropbox, gdata. Please wait..."
+#if ! pip install $ELEMT_SITE/$ELEMT_TB fasteners lockfile paramiko boto dropbox==6.9.0 gdata; then
+if ! pip install future fasteners paramiko boto dropbox==6.9.0 gdata; then
 	echo " failed"
 	exit 1
 fi
+
+echo "Python byte compiling..."
+python -m compileall /usr/lib/python$PVER/site-packages/duplicity >& /dev/null
+return 0
